title:            Talks by Nick Quinlan
description:      Talks given by Nick Quinlan
signoff:          Nick
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

root: /

links:
  - name:         About
    url:          http://nicholasquinlan.com
    external:     true
  - name:         Twitter
    url:          http://twitter.com/YayNickQ
    external:     true
  - name:         Email
    url:          mailto:nick@nicholasquinlan.com
    external:     true
  - name:         GitHub
    url:          http://github.com/nquinlan
    external:     true
pygments:         true
permalink:        pretty
google_analytics: UA-24562284-3
markdown:         rdiscount
rdiscount:
  extensions:     [smart,generate_toc]